# ifos_template_generator_stub_v1.py
from __future__ import annotations
from typing import List
import os

def generate(folder: str, files: List[str]) -> None:
    os.makedirs(folder, exist_ok=True)
    for f in files:
        path=os.path.join(folder, f)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        if not os.path.exists(path):
            with open(path,"w",encoding="utf-8") as fp:
                fp.write("# generated by IFOS stub\n")
